name: 运动自动调节程序

on:
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]
  schedule:
    - cron: "55 9 * * *" # 该时间为UTC时间，比北京时间晚8个小时
  # watch:
    # types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 开始
      run: |
        pip install requests
        pmode='${{ secrets.PMODE }}'
        pkey='${{ secrets.PKEY }}'
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
        ${pmode}
        ${pkey}
        ${user}
        ${pwd}
        ${step}
        EOF
